version: '3.8'

services:
  app:
    build: .
    container_name: idle_clans_app
    environment:
      RAILS_ENV: production
      DATABASE_URL: postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      REDIS_URL: redis://redis:6379/0
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      CLAN_NAME: ${CLAN_NAME:-RosaEinhorn}
      DISCORD_WEBHOOK_URL: ${DISCORD_WEBHOOK_URL}
    depends_on:
      - postgres
      - redis
    ports:
      - "3000:3000"
    volumes:
      - app_storage:/app/storage
    networks:
      - idle_clans_network
    restart: unless-stopped

  sidekiq:
    build: .
    container_name: idle_clans_sidekiq
    command: bundle exec sidekiq
    environment:
      RAILS_ENV: production
      DATABASE_URL: postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      REDIS_URL: redis://redis:6379/0
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      CLAN_NAME: ${CLAN_NAME:-RosaEinhorn}
      DISCORD_WEBHOOK_URL: ${DISCORD_WEBHOOK_URL}
    depends_on:
      - postgres
      - redis
    volumes:
      - app_storage:/app/storage
    networks:
      - idle_clans_network
    restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    container_name: idle_clans_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - idle_clans_network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: idle_clans_redis
    volumes:
      - redis_data:/data
    networks:
      - idle_clans_network
    restart: unless-stopped
    command: redis-server --appendonly yes

volumes:
  postgres_data:
  redis_data:
  app_storage:

networks:
  idle_clans_network:
    driver: bridge